# Generated by Django 6.0.4 on 2026-04-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='package',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
