# Generated by Django 6.0.4 on 2026-04-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_booking_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('support_staff', 'Support Staff'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
