# Generated by Django 6.0.4 on 2026-04-23 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_role'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE auth_users SET role='admin' WHERE is_staff = 1;",
            reverse_sql="UPDATE auth_users SET role='user' WHERE role='admin' AND is_staff = 0;"
        ),
    ]
