# Generated by Django 6.0.4 on 2026-05-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
